import type { Agent, HumanCall, Mission, MissionEvent, Project } from "./types";

/** Fixed clock so SSR + client seed data match. */
const now = 1_753_992_000_000; // 2025-07-31-ish fixed
const m = (mins: number) => now - mins * 60_000;


export const DEFAULT_PROJECT_ID = "proj_default";

export const SEED_PROJECTS: Project[] = [
  {
    id: DEFAULT_PROJECT_ID,
    name: "Demo board",
    slug: "default",
    description: "Shared demo board — create your own from the Boards rail",
    ownerUserId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj_platform",
    name: "Platform (demo)",
    slug: "platform",
    description: "Shared demo board for platform-style missions",
    ownerUserId: null,
    createdAt: now,
    updatedAt: now,
  },
];
export const SEED_AGENTS: Agent[] = [
  {
    id: "agent_hermes",
    name: "hermes",
    harness: "hermes",
    role: "Primary multi-tool agent",
    status: "online",
    skills: ["code", "terminal", "web", "delegate"],
    lastHeartbeat: m(0.3),
    currentMissionId: null,
    notes: "Hermes Agent — five-verb HTTP or MCP against Dev Boards.",
  },
  {
    id: "agent_grok",
    name: "grok",
    harness: "grok",
    role: "xAI Grok worker",
    status: "idle",
    skills: ["code", "reason", "review"],
    lastHeartbeat: m(2),
    currentMissionId: null,
    notes: "xAI Grok via API or Hermes provider — same board verbs.",
  },
  {
    id: "agent_omp",
    name: "omp",
    harness: "omp",
    role: "OMP runner",
    status: "offline",
    skills: ["batch", "pipeline"],
    lastHeartbeat: m(60),
    currentMissionId: null,
  },
  {
    id: "agent_openclaw",
    name: "openclaw",
    harness: "openclaw",
    role: "OpenClaw worker",
    status: "offline",
    skills: ["code", "tools"],
    lastHeartbeat: m(90),
    currentMissionId: null,
  },
  {
    id: "agent_scout",
    name: "scout",
    harness: "claude_code",
    role: "Research & intake",
    status: "online",
    skills: ["web", "summarize", "triage"],
    lastHeartbeat: m(0.4),
    currentMissionId: null,
  },
  {
    id: "agent_forge",
    name: "forge",
    harness: "codex",
    role: "Implementation",
    status: "busy",
    skills: ["code", "tests", "pr"],
    lastHeartbeat: m(0.2),
    currentMissionId: "msn_auth_hardening",
  },
  {
    id: "agent_lens",
    name: "lens",
    harness: "cursor",
    role: "Review & QA",
    status: "idle",
    skills: ["diff-review", "security", "perf"],
    lastHeartbeat: m(3),
    currentMissionId: null,
  },
  {
    id: "agent_relay",
    name: "relay",
    harness: "mcp",
    role: "Ops bridge / heartbeat",
    status: "online",
    skills: ["poll", "claim", "notify"],
    lastHeartbeat: m(0.1),
    currentMissionId: null,
    notes: "Harness-agnostic MCP bridge. Polls Ready, posts heartbeats.",
  },
  {
    id: "agent_night",
    name: "nightshift",
    harness: "opencode",
    role: "Overnight batch",
    status: "offline",
    skills: ["batch", "cleanup"],
    lastHeartbeat: m(140),
    currentMissionId: null,
  },
];

export const SEED_MISSIONS: Mission[] = [
  {
    id: "msn_auth_hardening",
    projectId: "proj_default",
    title: "Harden session cookie flags",
    objective:
      "Ensure auth cookies set Secure, HttpOnly, SameSite=Lax across preview and production hosts.",
    context:
      "Recent deploy showed preview cookie missing Secure under HTTPS proxy. Agents must not invent secrets.",
    constraints:
      "No new dependencies. Touch only cookie helper + tests. Keep Better Auth integration intact.",
    acceptance:
      "All session cookies include Secure+HttpOnly+SameSite. Unit tests green. Short delivery note with files touched.",
    column: "running",
    priority: "p0",
    tags: ["security", "auth"],
    assigneeId: "agent_forge",
    claimedBy: "agent_forge",
    claimedAt: m(18),
    lastHeartbeat: m(0.2),
    progressNote: "Updating cookie serializer; writing regression tests.",
    artifacts: [],
    createdAt: m(90),
    updatedAt: m(0.2),
  },
  {
    id: "msn_agent_protocol_doc",
    projectId: "proj_default",
    title: "Publish claim/heartbeat protocol card",
    objective:
      "Document the five agent verbs (poll, claim, heartbeat, escalate, deliver) for any harness.",
    context:
      "Operators keep pasting tickets into chats. We need one copy-paste contract.",
    constraints: "Single markdown brief. No product marketing fluff.",
    acceptance: "Protocol card in Review with sample JSON for each verb.",
    column: "ready",
    priority: "p1",
    tags: ["docs", "protocol"],
    assigneeId: null,
    claimedBy: null,
    claimedAt: null,
    lastHeartbeat: null,
    progressNote: "",
    artifacts: [],
    createdAt: m(200),
    updatedAt: m(40),
  },
  {
    id: "msn_latency_spike",
    projectId: "proj_platform",
    title: "Investigate agent heartbeat dropouts",
    objective:
      "Find why nightshift heartbeats stop after ~2h idle and propose fix.",
    context: "Logs show 408s from MCP bridge under load.",
    constraints: "Read-only investigation first. Escalate before code changes.",
    acceptance:
      "Root-cause note + recommended fix. Escalate if needs infra secrets.",
    column: "needs_human",
    priority: "p1",
    tags: ["ops", "reliability"],
    assigneeId: "agent_relay",
    claimedBy: "agent_relay",
    claimedAt: m(55),
    lastHeartbeat: m(4),
    progressNote: "Need decision: extend idle timeout or force re-auth?",
    artifacts: ["logs/heartbeat-drop-2026-07-30.txt"],
    createdAt: m(300),
    updatedAt: m(4),
  },
  {
    id: "msn_intake_ideas",
    projectId: "proj_default",
    title: "Triage weekend idea dump",
    objective: "Turn raw operator notes into 3–5 claimable missions.",
    context: "Slack dump in #agent-ops from last 48h.",
    constraints: "Do not start implementation. Output mission drafts only.",
    acceptance: "Draft missions ready in Inbox with priorities.",
    column: "inbox",
    priority: "p2",
    tags: ["triage"],
    assigneeId: "agent_scout",
    claimedBy: null,
    claimedAt: null,
    lastHeartbeat: null,
    progressNote: "",
    artifacts: [],
    createdAt: m(25),
    updatedAt: m(25),
  },
  {
    id: "msn_diff_review",
    projectId: "proj_default",
    title: "Review forge PR for cookie flags",
    objective: "Security pass on session cookie change before merge.",
    context: "Depends on msn_auth_hardening delivery.",
    constraints: "Focus on cookie flags, not style nits.",
    acceptance: "Approve or request changes with concrete diffs.",
    column: "inbox",
    priority: "p1",
    tags: ["review", "security"],
    assigneeId: "agent_lens",
    claimedBy: null,
    claimedAt: null,
    lastHeartbeat: null,
    progressNote: "",
    artifacts: [],
    createdAt: m(12),
    updatedAt: m(12),
  },
  {
    id: "msn_board_export",
    projectId: "proj_default",
    title: "JSON export of active missions",
    objective: "Ship one-click export of non-done missions for offline agents.",
    context: "Air-gapped harnesses need a file drop.",
    constraints: "Client-side only. No server write.",
    acceptance: "Export downloads valid JSON matching mission schema.",
    column: "review",
    priority: "p2",
    tags: ["feature"],
    assigneeId: "agent_forge",
    claimedBy: "agent_forge",
    claimedAt: m(400),
    lastHeartbeat: m(60),
    progressNote: "Export implemented; awaiting human acceptance.",
    artifacts: ["export-schema.v1.json"],
    createdAt: m(500),
    updatedAt: m(60),
    delivery: "Added Export Active button. Schema version 1.",
  },
  {
    id: "msn_dead_letter",
    projectId: "proj_default",
    title: "Retry failed image pipeline job",
    objective: "Re-run failed sprite sheet batch with fixed chroma key.",
    context: "Job died mid-sheet after magenta key mismatch.",
    constraints: "Do not reprocess successful assets.",
    acceptance: "Failed IDs cleared; board note with counts.",
    column: "blocked",
    priority: "p2",
    tags: ["assets"],
    assigneeId: null,
    claimedBy: null,
    claimedAt: null,
    lastHeartbeat: null,
    progressNote: "Blocked: missing source sheet path from operator.",
    artifacts: [],
    createdAt: m(800),
    updatedAt: m(120),
  },
  {
    id: "msn_onboard_mcp",
    projectId: "proj_default",
    title: "Register new MCP agent identity",
    objective: "Add agent identity for weekend research bot.",
    context: "Operator spinning up hermes profile.",
    constraints: "No secrets in board notes.",
    acceptance: "Agent online with role + skills; first heartbeat received.",
    column: "done",
    priority: "p3",
    tags: ["ops"],
    assigneeId: "agent_relay",
    claimedBy: "agent_relay",
    claimedAt: m(1000),
    lastHeartbeat: m(900),
    progressNote: "",
    artifacts: [],
    createdAt: m(1200),
    updatedAt: m(900),
    delivery: "Agent scout registered; first heartbeat at T+2m.",
  },
];

export const SEED_CALLS: HumanCall[] = [
  {
    id: "call_idle_timeout",
    missionId: "msn_latency_spike",
    agentId: "agent_relay",
    question:
      "Heartbeat dropouts after 2h idle — extend idle timeout to 6h, or force re-auth every 90m?",
    urgency: "p1",
    createdAt: m(12),
    resolvedAt: null,
    reply: null,
  },
];

export const SEED_EVENTS: MissionEvent[] = [
  {
    id: "ev1",
    missionId: "msn_auth_hardening",
    agentId: "agent_forge",
    kind: "heartbeat",
    message: "forge heartbeat · cookie serializer 60%",
    at: m(0.2),
  },
  {
    id: "ev2",
    missionId: "msn_latency_spike",
    agentId: "agent_relay",
    kind: "escalation",
    message: "relay escalated · needs decision on idle timeout",
    at: m(12),
  },
  {
    id: "ev3",
    missionId: "msn_board_export",
    agentId: "agent_forge",
    kind: "delivery",
    message: "forge delivered · awaiting review",
    at: m(60),
  },
  {
    id: "ev4",
    missionId: "msn_agent_protocol_doc",
    agentId: null,
    kind: "mission_created",
    message: "Mission queued in Ready for any harness",
    at: m(40),
  },
  {
    id: "ev5",
    missionId: null,
    agentId: "agent_scout",
    kind: "agent_status",
    message: "scout online · Claude Code",
    at: m(5),
  },
];
